### ISSUE TITLE
Plugin registation fails in Intellij12: Unsupported major.minor version 51.0

### ISSUE THREAD

**Issue by adben** [ahanin/intellij-jalopy-plugin#1]
Intellij 12(12.0.3 build 123.155) fails to register the plugin due unsupported major.minor version 51.0

the exception: 
com/alexeyhanin/intellij/jalopyplugin/component/JalopyPluginRegistration : Unsupported major.minor version 51.0 [Plugin: com.alexeyhanin.intellij.jalopyplugin]: com/alexeyhanin/intellij/jalopyplugin/component/JalopyPluginRegistration : Unsupported major.minor version 51.0 [Plugin: com.alexeyhanin.intellij.jalopyplugin]
com.intellij.diagnostic.PluginException: com/alexeyhanin/intellij/jalopyplugin/component/JalopyPluginRegistration : Unsupported major.minor version 51.0 [Plugin: com.alexeyhanin.intellij.jalopyplugin]
    at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentsRegistry.a(ComponentManagerImpl.java:470)
    at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentsRegistry.a(ComponentManagerImpl.java:435)
    at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentsRegistry.access$000(ComponentManagerImpl.java:421)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.a(ComponentManagerImpl.java:102)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.initComponents(ComponentManagerImpl.java:346)
    at com.intellij.openapi.components.impl.stores.ApplicationStoreImpl.load(ApplicationStoreImpl.java:83)
    at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:554)
    at com.intellij.idea.IdeaApplication.run(IdeaApplication.java:199)
    at com.intellij.idea.MainImpl$3.run(MainImpl.java:160)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:209)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:702)
    at java.awt.EventQueue.access$400(EventQueue.java:82)
    at java.awt.EventQueue$2.run(EventQueue.java:663)
    at java.awt.EventQueue$2.run(EventQueue.java:661)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:87)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:672)
    at com.intellij.ide.IdeEventQueue.d(IdeEventQueue.java:673)
    at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:498)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:333)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:296)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:211)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:196)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:188)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:122)
Caused by: java.lang.UnsupportedClassVersionError: com/alexeyhanin/intellij/jalopyplugin/component/JalopyPluginRegistration : Unsupported major.minor version 51.0
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClassCond(ClassLoader.java:631)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:615)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:465)
    at com.intellij.util.lang.UrlClassLoader._defineClass(UrlClassLoader.java:131)
    at com.intellij.util.lang.UrlClassLoader.defineClass(UrlClassLoader.java:127)
    at com.intellij.util.lang.UrlClassLoader._findClass(UrlClassLoader.java:103)
    at com.intellij.ide.plugins.cl.PluginClassLoader.d(PluginClassLoader.java:102)
    at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:63)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:247)
    at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentsRegistry.a(ComponentManagerImpl.java:445)
    ... 25 more

**Comment by ahanin** [comment]
The plugin is repackaged for Java 6, since IntelliJ IDEA 12 is built on Java 6 already. It has been updated in repository and it can take a while before it gets approved. Alternatively, you can build your local package with Java 6 by adjusting Java Compiler settings and 'preparing plugin module for deploying'.

**Comment by adben** [comment]
The issue persist, environment information;
jalopi plugin version: 1.0.1
intellij build: 123.168
osx: 10.8.2
jdk: 1.6.0_38

Error;
com/alexeyhanin/intellij/jalopyplugin/action/FormatAction : Unsupported major.minor version 51.0 [Plugin: com.alexeyhanin.intellij.jalopyplugin]: com/alexeyhanin/intellij/jalopyplugin/action/FormatAction : Unsupported major.minor version 51.0 [Plugin: com.alexeyhanin.intellij.jalopyplugin]
com.intellij.diagnostic.PluginException: com/alexeyhanin/intellij/jalopyplugin/action/FormatAction : Unsupported major.minor version 51.0 [Plugin: com.alexeyhanin.intellij.jalopyplugin]
    at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.a(ActionManagerImpl.java:266)
    at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.a(ActionManagerImpl.java:228)
    at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.getAction(ActionManagerImpl.java:221)
    at com.intellij.openapi.actionSystem.DefaultActionGroup.unstub(DefaultActionGroup.java:281)
    at com.intellij.openapi.actionSystem.DefaultActionGroup.getChildren(DefaultActionGroup.java:248)
    at com.intellij.openapi.actionSystem.impl.ActionManagerImpl$5.compute(ActionManagerImpl.java:1155)
    at com.intellij.openapi.actionSystem.impl.ActionManagerImpl$5.compute(ActionManagerImpl.java:1149)
    at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:956)
    at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.a(ActionManagerImpl.java:1149)
    at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.a(ActionManagerImpl.java:1163)
    at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.a(ActionManagerImpl.java:1163)
    at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.preloadActionGroup(ActionManagerImpl.java:1143)
    at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.d(ActionManagerImpl.java:1135)
    at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.access$200(ActionManagerImpl.java:69)
    at com.intellij.openapi.actionSystem.impl.ActionManagerImpl$4.run(ActionManagerImpl.java:1118)
    at com.intellij.openapi.application.impl.ApplicationImpl$6.run(ApplicationImpl.java:465)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:439)
    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
    at java.util.concurrent.FutureTask.run(FutureTask.java:138)
    at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
    at java.lang.Thread.run(Thread.java:680)
    at com.intellij.openapi.application.impl.ApplicationImpl$1$1.run(ApplicationImpl.java:153)
Caused by: java.lang.UnsupportedClassVersionError: com/alexeyhanin/intellij/jalopyplugin/action/FormatAction : Unsupported major.minor version 51.0
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClassCond(ClassLoader.java:631)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:615)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:465)
    at com.intellij.util.lang.UrlClassLoader._defineClass(UrlClassLoader.java:131)
    at com.intellij.util.lang.UrlClassLoader.defineClass(UrlClassLoader.java:127)
    at com.intellij.util.lang.UrlClassLoader._findClass(UrlClassLoader.java:103)
    at com.intellij.ide.plugins.cl.PluginClassLoader.d(PluginClassLoader.java:102)
    at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:63)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:247)
    at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.a(ActionManagerImpl.java:250)
    ... 22 more

**Comment by ahanin** [comment]
@adben Sorry, cannot reproduce:

java -version
java version "1.6.0_38"
Java(TM) SE Runtime Environment (build 1.6.0_38-b05)
Java HotSpot(TM) 64-Bit Server VM (build 20.13-b02, mixed mode)

DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=12.10
DISTRIB_CODENAME=quantal
DISTRIB_DESCRIPTION="Ubuntu 12.10"
NAME="Ubuntu"
VERSION="12.10, Quantal Quetzal"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu quantal (12.10)"
VERSION_ID="12.10"

idea-IU-123.72

"Unsupported major.minor version 51.0" means that you still use the old package which was packaged with target Java 7.

Try the following:
1. uninstall the plugin
2. install from the repository
