### ISSUE TITLE
Intellij IDEA 13

### ISSUE THREAD

**Issue by SEGEEK** [ahanin/intellij-jalopy-plugin#3]
Are there any plans for Intellij 13 support?  There are a lot of exceptions that get thrown when the plugin runs there now.

**Comment by ahanin** [comment]
Hi,

I'm not actively 'developing' the plugin, but I can take a look into the problem. Could you please give me your Java version, and the IntelliJ build number? Also, please, put a error stacktrace here. And describe the steps the lead to that.

**Comment by SEGEEK** [comment]
Build number is IU-135.909.  I am using java 1.7.0_51, I can generate some
log files of the exceptions being thrown if that would be useful.

I am appending the log file error that keeps getting repeated, I am
guessing IDEA 13 doesn't allow you to do something that 12 did, because the
plugin works beautifully there.
Thanks, I appreciate any help you can provide.

2014-07-16 18:25:00,358 [13937337]  ERROR - .psi.impl.DocumentCommitThread
- IntelliJ IDEA 13.1.3  Build #IU-135.909
  2014-07-16 18:25:00,358 [13937337]  ERROR - .psi.impl.DocumentCommitThread
- JDK: 1.7.0_40
  2014-07-16 18:25:00,358 [13937337]  ERROR - .psi.impl.DocumentCommitThread
- VM: Java HotSpot(TM) Server VM
  2014-07-16 18:25:00,358 [13937337]  ERROR - .psi.impl.DocumentCommitThread
- Vendor: Oracle Corporation
  2014-07-16 18:25:00,358 [13937337]  ERROR - .psi.impl.DocumentCommitThread
- OS: Windows 7
  2014-07-16 18:25:00,358 [13937337]  ERROR - .psi.impl.DocumentCommitThread
- Last Action: EditorUp
  2014-07-16 18:25:00,358 [13937337]  ERROR - .psi.impl.DocumentCommitThread
- Current Command: Format with Jalopy
  2014-07-16 18:25:01,777 [13938756]  ERROR - .psi.impl.DocumentCommitThread
- Must not modify PSI inside save listener
  com.intellij.util.IncorrectOperationException: Must not modify PSI inside
  save listener
  at
  com.intellij.pom.core.impl.PomModelImpl.runTransaction(PomModelImpl.java:139)
  at
  com.intellij.psi.impl.DocumentCommitProcessor.doActualPsiChange(DocumentCommitProcessor.java:174)
  at
  com.intellij.psi.impl.DocumentCommitProcessor$1$1.run(DocumentCommitProcessor.java:142)
  at
  com.intellij.psi.impl.source.codeStyle.CodeStyleManagerImpl$8.compute(CodeStyleManagerImpl.java:669)
  at
  com.intellij.psi.impl.source.PostprocessReformattingAspect.disablePostprocessFormattingInside(PostprocessReformattingAspect.java:116)
  at
  com.intellij.psi.impl.source.codeStyle.CodeStyleManagerImpl$10.compute(CodeStyleManagerImpl.java:704)
  at
  com.intellij.formatting.FormatterImpl.runWithFormattingDisabled(FormatterImpl.java:812)
  at
  com.intellij.psi.impl.source.codeStyle.CodeStyleManagerImpl.performActionWithFormatterDisabled(CodeStyleManagerImpl.java:700)
  at
  com.intellij.psi.impl.source.codeStyle.CodeStyleManagerImpl.performActionWithFormatterDisabled(CodeStyleManagerImpl.java:666)
  at
  com.intellij.psi.impl.DocumentCommitProcessor$1.process(DocumentCommitProcessor.java:138)
  at
  com.intellij.psi.impl.DocumentCommitProcessor$1.process(DocumentCommitProcessor.java:128)
  at
  com.intellij.psi.impl.PsiDocumentManagerBase.finishCommitInWriteAction(PsiDocumentManagerBase.java:323)
  at
  com.intellij.psi.impl.PsiDocumentManagerImpl.finishCommitInWriteAction(PsiDocumentManagerImpl.java:141)
  at
  com.intellij.psi.impl.PsiDocumentManagerBase$2.run(PsiDocumentManagerBase.java:291)
  at
  com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:984)
  at
  com.intellij.psi.impl.PsiDocumentManagerBase.finishCommit(PsiDocumentManagerBase.java:288)
  at
  com.intellij.psi.impl.DocumentCommitThread$4.run(DocumentCommitThread.java:477)
  at
  com.intellij.psi.impl.DocumentCommitThread.commitSynchronously(DocumentCommitThread.java:371)
  at
  com.intellij.psi.impl.PsiDocumentManagerBase$4.run(PsiDocumentManagerBase.java:374)
  at
  com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:984)
  at
  com.intellij.psi.impl.PsiDocumentManagerBase.a(PsiDocumentManagerBase.java:366)
  at
  com.intellij.psi.impl.PsiDocumentManagerBase.commitDocument(PsiDocumentManagerBase.java:278)
  at com.triemax.l.run(l.java:3)
  at
  com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:984)
  at com.triemax.b1b.run(b1b.java:3)
  at
  com.intellij.openapi.command.impl.CommandProcessorImpl.executeCommand(CommandProcessorImpl.java:124)
  at
  com.intellij.openapi.command.impl.CommandProcessorImpl.executeCommand(CommandProcessorImpl.java:99)
  at
  com.intellij.openapi.command.impl.CommandProcessorImpl.executeCommand(CommandProcessorImpl.java:85)
  at com.triemax.npb.a(npb.java:44)
  at com.triemax.npb.a(npb.java:23)
  at com.triemax.i4.run(i4.java:3)
  at
  com.intellij.openapi.editor.impl.FoldingModelImpl.a(FoldingModelImpl.java:214)
  at
  com.intellij.openapi.editor.impl.FoldingModelImpl.runBatchFoldingOperation(FoldingModelImpl.java:194)
  at com.triemax.w.a(w.java:22)
  at com.triemax.ozb.run(ozb.java:26)
  at com.triemax.f2b.a(f2b.java:1)
  at com.triemax.f2b.a(f2b.java:4)
  at com.triemax.uob.a(uob.java:7)
  at com.triemax.mfb.a(mfb.java:638)
  at com.triemax.mfb.b(mfb.java:63)
  at com.triemax.ofb.b(ofb.java:100)
  at com.triemax.mfb.a(mfb.java:465)
  at com.triemax.mfb.a(mfb.java:517)
  at com.triemax.ofb.a(ofb.java:93)
  at com.triemax.llb.g(llb.java:2)
  at com.triemax.fwb.a(fwb.java:2)
  at com.triemax.h7b.run(h7b.java:5)
  at com.triemax.jlb.run(jlb.java:45)
  at java.lang.Thread.run(Thread.java:724)
  at com.triemax.f2b.a(f2b.java:1)
  at com.triemax.uob.b(uob.java:1)
  at com.triemax.jlb.h(jlb.java:31)
  at com.triemax.mfb.b(mfb.java:619)
  at com.triemax.mfb.a(mfb.java:408)
  at com.triemax.mfb.a(mfb.java:491)
  at com.triemax.ofb.a(ofb.java:233)
  at com.triemax.ofb.a(ofb.java:152)
  at com.triemax.yl.handle(yl.java:3)
  at
  com.intellij.util.messages.impl.MessageBusConnectionImpl.deliverMessage(MessageBusConnectionImpl.java:111)
  at
  com.intellij.util.messages.impl.MessageBusImpl.doPumpMessages(MessageBusImpl.java:228)
  at
  com.intellij.util.messages.impl.MessageBusImpl.pumpMessages(MessageBusImpl.java:219)
  at
  com.intellij.util.messages.impl.MessageBusImpl.sendMessage(MessageBusImpl.java:209)
  at
  com.intellij.util.messages.impl.MessageBusImpl.access$000(MessageBusImpl.java:43)
  at
  com.intellij.util.messages.impl.MessageBusImpl$1.invoke(MessageBusImpl.java:131)
  at com.sun.proxy.$Proxy18.beforeDocumentSaving(Unknown Source)
  at sun.reflect.GeneratedMethodAccessor87.invoke(Unknown Source)
  at
  sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:606)
  at
  com.intellij.openapi.fileEditor.impl.FileDocumentManagerImpl.a(FileDocumentManagerImpl.java:127)
  at
  com.intellij.openapi.fileEditor.impl.FileDocumentManagerImpl.access$000(FileDocumentManagerImpl.java:87)
  at
  com.intellij.openapi.fileEditor.impl.FileDocumentManagerImpl$1.invoke(FileDocumentManagerImpl.java:115)
  at com.sun.proxy.$Proxy18.beforeDocumentSaving(Unknown Source)
  at
  com.intellij.openapi.fileEditor.impl.FileDocumentManagerImpl$5.run(FileDocumentManagerImpl.java:427)
  at
  com.intellij.pom.core.impl.PomModelImpl.guardPsiModificationsIn(PomModelImpl.java:340)
  at
  com.intellij.openapi.fileEditor.impl.FileDocumentManagerImpl.a(FileDocumentManagerImpl.java:424)
  at
  com.intellij.openapi.fileEditor.impl.FileDocumentManagerImpl.a(FileDocumentManagerImpl.java:398)
  at
  com.intellij.openapi.fileEditor.impl.FileDocumentManagerImpl.saveAllDocuments(FileDocumentManagerImpl.java:319)
  at
  com.intellij.openapi.fileEditor.impl.FileDocumentManagerImpl.saveAllDocuments(FileDocumentManagerImpl.java:298)
  at
  com.intellij.openapi.application.impl.ApplicationImpl.saveAll(ApplicationImpl.java:1429)
  at
  com.intellij.ide.actions.SaveAllAction.actionPerformed(SaveAllAction.java:26)
  at
  com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$3.performAction(IdeKeyEventDispatcher.java:564)
  at
  com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:611)
  at
  com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.d(IdeKeyEventDispatcher.java:463)
  at
  com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:206)
  at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:493)
  at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:335)
  at
  java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
  at
  java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
  at
  java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
  at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
  at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
  at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)
